version: '3.8'

services:
  postgres:
    container_name: 'Postgres'
    image: 'postgres:16.1-alpine3.19'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgrespasswd
      POSTGRES_DB: safblog
